name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff black mypy pytest pytest-cov
      - name: Lint
        run: |
          ruff .
          black --check .
      - name: Type check
        run: mypy .
      - name: Test with coverage
        run: |
          pytest --cov=tests --cov-report=xml
      - name: Verify coverage
        run: |
          python - <<'PY'
import xml.etree.ElementTree as ET, sys
rate = float(ET.parse('coverage.xml').getroot().get('line-rate'))
if rate < 0.9:
    print(f'Coverage {rate*100:.1f}% below 90%')
    sys.exit(1)
PY
      - name: Build Docker image
        run: docker build -t fastapi-operator-env:ci .

